# Version: 0.0.1
FROM ubuntu
RUN apt-get update
RUN apt install -y man
#RUN apt install -y exim4
RUN apt install -y openssl
RUN apt install -y vim

#docker rmi my:mail -f
#docker build -t my:mail .
#docker run -it my:mail
#https://www.digitalocean.com/community/tutorials/how-to-install-the-send-only-mail-server-exim-on-ubuntu-12-04
#echo "This is a test." | mail -s Testing someone@somedomain.tld
