# Version: 0.0.1
FROM ubuntu
RUN apt-get update
RUN apt install -y man
#RUN apt install -y exim4
RUN apt install -y openssl
RUN apt install -y vim

#docker rmi my:mail -f
#docker build -t my:mail .
#docker run -it my:mail
